-- MySQL Script generated by MySQL Workbench
-- Sun May 11 16:29:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `CPF` VARCHAR(13) NOT NULL,
  `Telefone` INT(15) NOT NULL,
  `Endereco` VARCHAR(50) NOT NULL,
  `RG` VARCHAR(15) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Telefone_UNIQUE` (`Telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caracteristicas` (
  `idCaracteristicas` INT NOT NULL,
  `Esporte` VARCHAR(20) NOT NULL,
  `Funçao` VARCHAR(20) NOT NULL,
  `Area forte` VARCHAR(15) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCaracteristicas`, `Pessoa_idPessoa`),
  INDEX `fk_Caracteristicas_Pessoa_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Caracteristicas_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clube` (
  `idClube` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(10) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Registro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClube`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peneira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peneira` (
  `idPeneira` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Horario` DATETIME NOT NULL,
  `Local` VARCHAR(20) NOT NULL,
  `Descricao` TEXT NOT NULL,
  `Horario_fechamento` DATETIME NOT NULL,
  `Vagas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeneira`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL,
  `comentario` TEXT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idComentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario_has_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario_has_Pessoa` (
  `Comentario_idComentario` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Comentario_idComentario`, `Pessoa_idPessoa`),
  INDEX `fk_Comentario_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Comentario_has_Pessoa_Comentario1_idx` (`Comentario_idComentario` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_has_Pessoa_Comentario1`
    FOREIGN KEY (`Comentario_idComentario`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario_has_Clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario_has_Clube` (
  `Comentario_idComentario` INT NOT NULL,
  `Clube_idClube` INT NOT NULL,
  PRIMARY KEY (`Comentario_idComentario`, `Clube_idClube`),
  INDEX `fk_Comentario_has_Clube_Clube1_idx` (`Clube_idClube` ASC) VISIBLE,
  INDEX `fk_Comentario_has_Clube_Comentario1_idx` (`Comentario_idComentario` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_has_Clube_Comentario1`
    FOREIGN KEY (`Comentario_idComentario`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_has_Clube_Clube1`
    FOREIGN KEY (`Clube_idClube`)
    REFERENCES `mydb`.`Clube` (`idClube`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clube_has_Peneira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clube_has_Peneira` (
  `Clube_idClube` INT NOT NULL,
  `Peneira_idPeneira` INT NOT NULL,
  PRIMARY KEY (`Clube_idClube`, `Peneira_idPeneira`),
  INDEX `fk_Clube_has_Peneira_Peneira1_idx` (`Peneira_idPeneira` ASC) VISIBLE,
  INDEX `fk_Clube_has_Peneira_Clube1_idx` (`Clube_idClube` ASC) VISIBLE,
  CONSTRAINT `fk_Clube_has_Peneira_Clube1`
    FOREIGN KEY (`Clube_idClube`)
    REFERENCES `mydb`.`Clube` (`idClube`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clube_has_Peneira_Peneira1`
    FOREIGN KEY (`Peneira_idPeneira`)
    REFERENCES `mydb`.`Peneira` (`idPeneira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peneira_has_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peneira_has_Pessoa` (
  `Peneira_idPeneira` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`Peneira_idPeneira`, `Pessoa_idPessoa`),
  INDEX `fk_Peneira_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Peneira_has_Pessoa_Peneira1_idx` (`Peneira_idPeneira` ASC) VISIBLE,
  CONSTRAINT `fk_Peneira_has_Pessoa_Peneira1`
    FOREIGN KEY (`Peneira_idPeneira`)
    REFERENCES `mydb`.`Peneira` (`idPeneira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peneira_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
